"""initial schema

Revision ID: 5c810c496475
Revises: 
Create Date: 2026-08-07 18:04:47.262647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5c810c496475'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('correlation_library',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('family_key', sa.String(length=32), nullable=False),
    sa.Column('ln_mfi_coefficient', sa.Float(), nullable=False),
    sa.Column('ea_kj_mol', sa.Float(), nullable=False),
    sa.Column('reference_temp_C', sa.Float(), nullable=False),
    sa.Column('reference_residence_time_min', sa.Float(), nullable=False),
    sa.Column('source_citation', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('approved_by', sa.String(length=128), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('superseded_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['superseded_by_id'], ['correlation_library.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('family_key', 'version', name='uq_correlation_family_version')
    )
    op.create_index(op.f('ix_correlation_library_family_key'), 'correlation_library', ['family_key'], unique=False)
    op.create_table('grades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grade_id', sa.String(length=64), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('source_pdf', sa.String(length=255), nullable=False),
    sa.Column('family', sa.String(length=32), nullable=False),
    sa.Column('filler_type', sa.String(length=32), nullable=False),
    sa.Column('filler_content_pct', sa.Float(), nullable=True),
    sa.Column('density_kg_m3', sa.Float(), nullable=True),
    sa.Column('mould_shrinkage_pct', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grades_grade_id'), 'grades', ['grade_id'], unique=True)
    op.create_table('properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grade_pk', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('property_class', sa.String(length=32), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('condition', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('test_method', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['grade_pk'], ['grades.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('grade_pk', 'key', 'condition', name='uq_property_grade_key_condition')
    )
    op.create_index(op.f('ix_properties_grade_pk'), 'properties', ['grade_pk'], unique=False)
    op.create_index(op.f('ix_properties_key'), 'properties', ['key'], unique=False)
    op.create_table('raw_pdf_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grade_pk', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.String(length=512), nullable=False),
    sa.ForeignKeyConstraint(['grade_pk'], ['grades.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_pdf_files_grade_pk'), 'raw_pdf_files', ['grade_pk'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_raw_pdf_files_grade_pk'), table_name='raw_pdf_files')
    op.drop_table('raw_pdf_files')
    op.drop_index(op.f('ix_properties_key'), table_name='properties')
    op.drop_index(op.f('ix_properties_grade_pk'), table_name='properties')
    op.drop_table('properties')
    op.drop_index(op.f('ix_grades_grade_id'), table_name='grades')
    op.drop_table('grades')
    op.drop_index(op.f('ix_correlation_library_family_key'), table_name='correlation_library')
    op.drop_table('correlation_library')
    # ### end Alembic commands ###
