"""add pending_correlations review queue

Revision ID: 80e005ccd701
Revises: dd428aefdf00
Create Date: 2026-08-07 20:51:00.242611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '80e005ccd701'
down_revision: Union[str, Sequence[str], None] = 'dd428aefdf00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_correlations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('family_key', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('proposed_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('search_summary', sa.Text(), nullable=False),
    sa.Column('reviewer_notes', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by', sa.String(length=128), nullable=True),
    sa.Column('promoted_correlation_pk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['promoted_correlation_pk'], ['correlation_library.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pending_correlations_family_key'), 'pending_correlations', ['family_key'], unique=False)
    op.create_index(op.f('ix_pending_correlations_status'), 'pending_correlations', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pending_correlations_status'), table_name='pending_correlations')
    op.drop_index(op.f('ix_pending_correlations_family_key'), table_name='pending_correlations')
    op.drop_table('pending_correlations')
    # ### end Alembic commands ###
